import { NextResponse } from 'next/server';

export async function GET() {
  const envVars = {
    // Firebase Admin
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID ? 'SET' : 'MISSING',
    FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL ? 'SET' : 'MISSING',
    FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY ? 'SET' : 'MISSING',
    
    // Stripe
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY ? 'SET' : 'MISSING',
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY ? 'SET' : 'MISSING',
    
    // CSRF
    CSRF_SECRET_KEY: process.env.CSRF_SECRET_KEY ? 'SET' : 'MISSING',
    
    // Stripe Price IDs (Server-side)
    STRIPE_STARTER_MONTHLY_PRICE_ID: process.env.STRIPE_STARTER_MONTHLY_PRICE_ID ? 'SET' : 'MISSING',
    STRIPE_STARTER_YEARLY_PRICE_ID: process.env.STRIPE_STARTER_YEARLY_PRICE_ID ? 'SET' : 'MISSING',
    STRIPE_GROWTH_MONTHLY_PRICE_ID: process.env.STRIPE_GROWTH_MONTHLY_PRICE_ID ? 'SET' : 'MISSING',
    STRIPE_GROWTH_YEARLY_PRICE_ID: process.env.STRIPE_GROWTH_YEARLY_PRICE_ID ? 'SET' : 'MISSING',
    STRIPE_PRO_MONTHLY_PRICE_ID: process.env.STRIPE_PRO_MONTHLY_PRICE_ID ? 'SET' : 'MISSING',
    STRIPE_PRO_YEARLY_PRICE_ID: process.env.STRIPE_PRO_YEARLY_PRICE_ID ? 'SET' : 'MISSING',
    
    // Stripe Price IDs (Client-side)
    NEXT_PUBLIC_STRIPE_STARTER_MONTHLY_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_STARTER_MONTHLY_PRICE_ID ? 'SET' : 'MISSING',
    NEXT_PUBLIC_STRIPE_STARTER_YEARLY_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_STARTER_YEARLY_PRICE_ID ? 'SET' : 'MISSING',
    NEXT_PUBLIC_STRIPE_GROWTH_MONTHLY_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_GROWTH_MONTHLY_PRICE_ID ? 'SET' : 'MISSING',
    NEXT_PUBLIC_STRIPE_GROWTH_YEARLY_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_GROWTH_YEARLY_PRICE_ID ? 'SET' : 'MISSING',
    NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PRICE_ID ? 'SET' : 'MISSING',
    NEXT_PUBLIC_STRIPE_PRO_YEARLY_PRICE_ID: process.env.NEXT_PUBLIC_STRIPE_PRO_YEARLY_PRICE_ID ? 'SET' : 'MISSING',
  };

  return NextResponse.json({
    message: 'Environment Variables Status',
    environment: process.env.NODE_ENV,
    variables: envVars,
    timestamp: new Date().toISOString()
  });
} 